main = "src/index.ts"
compatibility_date = "2022-05-12"
workers_dev = true

[triggers]
crons = ["0 0 * * *"]

[env.production]
name = "analytics-pulpproject-org"
kv_namespaces = [
  { binding = "RAW", id = "4e3a9bbd8ae542828ccf63030e844759", preview_id = "4e3a9bbd8ae542828ccf63030e844759" },
  { binding = "SUMMARY", id = "7ddbf45f05ae4619a88cb997af71188d", preview_id = "7ddbf45f05ae4619a88cb997af71188d" }
]
vars = {WORKER_ENV = "production"}


[env.dev]
name = "dev-analytics-pulpproject-org"
kv_namespaces = [
  { binding = "RAW", id = "bd79a1c491ce493ea41856a4182baf67", preview_id = "bd79a1c491ce493ea41856a4182baf67" },
  { binding = "SUMMARY", id = "5cf21dbae6484fbabeea9e8593e90daf", preview_id = "5cf21dbae6484fbabeea9e8593e90daf" }
]
vars = {WORKER_ENV = "dev"}
