main = "src/index.ts"
compatibility_date = "2022-05-12"
workers_dev = true

[triggers]
crons = ["0 0 * * *"]

[env.production]
name = "analytics-pulpproject-org"
kv_namespaces = [
  { binding = "RAW", id = "4e3a9bbd8ae542828ccf63030e844759", preview_id = "4e3a9bbd8ae542828ccf63030e844759" },
  { binding = "SUMMARY", id = "7ddbf45f05ae4619a88cb997af71188d", preview_id = "7ddbf45f05ae4619a88cb997af71188d" }
]
vars = {WORKER_ENV = "production"}


[env.dev]
name = "dev-analytics-pulpproject-org"
kv_namespaces = [
  { binding = "RAW", id = "fab96d2472434d31a359d17d2cbf88f6", preview_id = "fab96d2472434d31a359d17d2cbf88f6" },
  { binding = "SUMMARY", id = "5d9e079ee0124d4eb59dde18b72c2095", preview_id = "5d9e079ee0124d4eb59dde18b72c2095" }
]
vars = {WORKER_ENV = "dev"}
