import { handlePost } from "./handlers/post";


const html = `<!DOCTYPE html>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker.</p>
</body>`;


addEventListener('fetch', event => {
  if (event.request.method === "POST") {
    event.respondWith(handlePost(event.request));
  } else {
    event.respondWith(new Response(null, { status: 405 }));
  }
});

