import { handleGet } from "./handlers/get";
import { handlePost } from "./handlers/post";
import { handleSchedule } from "./handlers/schedule";
import {CfRequest} from "./data";


const html = `<!DOCTYPE html>
<body>
  <h1>Hello World</h1>
  <p>This markup was generated by a Cloudflare Worker.</p>
</body>`;


addEventListener('fetch', event => {
  if (event.request.method === "GET") {
    event.respondWith(handleGet(event.request));
  } else if (event.request.method === "POST") {
    event.respondWith(handlePost(event.request));
  } else if (event.request.method === "PUT") {
    if (WORKER_ENV == "dev") {
      // let's only allow manual triggering in the 'dev' environment
      event.respondWith(handleSchedule());
    }
  } else {
    event.respondWith(new Response(null, { status: 405 }));
  }
});

addEventListener("scheduled", (event) => {
  event.waitUntil(handleSchedule());
});
